#######################
# Theme Customization #
#######################

title: lokii                             # used in <title> tag & site header
author: loki-pup                        # used in a <meta> tag & /feed.xml
description: >                              # used in a <meta> tag & /feed.xml
  A DOG LOVER'S BLOG
slogan: i!!!                           # used in site header, beside title
avatar: /i/bobo.png                       # used as portrait in site header
banner: /i/mountains.svg                    # used as background in site header
url: http://loki-pup.github.io              # used by plugins to generate feed.xml and sitemap.xml
baseurl: ''                                 # prepended to all absolute filepaths
repo: https://github.com/loki-pup # used in footer

# Objects listed here will appear in the main nav menu.
# Exceeding four items may cause problems on the desktop (>900px wide) layout.
nav_menu:
  - name: Posts
    url: /
    icon: /i/icons.svg#posts # icons should be 24x24 px.
#  - name: Projects
#    url: /projects
#    icon: /i/icons.svg#portfolio
  - name: GitHub
    url: https://github.com/loki-pup
    icon: /i/icons.svg#github
    outbound: true      # this key sets a link to open in a new window.
  - name: About
    url: /about
#    scheme: mailto      # these keys enable email obfuscation.
#    handle: hello       # you know, to protect you from bots. (handle and domain
#    domain: github.com  # are separated in case bots crawl GitHub repos, too.)
    icon: /i/info-24px.svg

# Objects listed here will appear on the /projects.html page.
#projects:
 # - title: Solana
 #  teaser: A responsive blog template written in Sass and vanilla JavaScript.
 #   url: https://github.com/rlue/jekyll-solana
 #   role: Creator
 #   category: Frontend Dev
 # - title: Cortana
 #   teaser: A talking robot. Now available on Google Play?
 #   url: https://play.google.com/store/apps/details?id=com.microsoft.cortana
 #   role: Core Team
 #   category: NLP
 # - title: Rihanna
 #   teaser: Possibly another robot. Also available on Google Play.
 #   url: https://play.google.com/store/music/artist/Rihanna?id=Arcw2m2ih45qntv3fufub25tyhu
 #   role: Contributor
  #  category: Algorithmic Composition

#################
# Site Settings #
#################

incremental: true
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - TODO.md

permalink: /:collection/:path

collections:
  category: { output: true }
  tag:      { output: true }

defaults:
  - scope:  { type:   posts    }
    values: { layout: post     }
  - scope:  { type:   tag      }
    values: { layout: listing  }
  - scope:  { type:   category }
    values: { layout: listing  }

sass:
  sass_dir: _assets/css

plugins:
  - jekyll-paginate
  - jekyll-feed
  - jekyll-sitemap

paginate: 10
